### ISSUE TITLE
App doesn't prompt to update old mobility (1.3.7) but to install 

### ISSUE THREAD

**Issue by ctrance** [ohmage/android-lib#46]
This test case has failed >>If an old version of mobility is installed verify that the mobility activity displays a message telling the user to make sure mobility is up to date<<

I was prompted to install mobility instead of updating old version.

**Comment by cketcham** [comment]
This is actually caused because the older version of mobility had a different package name so it is technically correct to require them to install (rather than upgrade mobility). In 2.15 all versions of mobility with the package name org.ohmage.mobility are compatible, so this test is no longer necessary.
