### ISSUE TITLE
Adding GPS_OFF as one of locationStatus associated with GPS 

### ISSUE THREAD

**Issue by hongsudt** [ohmage/android-lib#64]
When GPS data is not available, we want to distinguish between the cases when GPS is off vs. when there is no GPS signal. This can be done by adding an additional status (i.e. GPS_OFF) to locationStatus associated with GPS within each survey response. 

I like this since the same request can be applied to ohmage-mwf as well..

**Comment by jshslsky** [comment]
Should this be in the WiFiGPSLocation repo issue tracker?

**Comment by cketcham** [comment]
ohmage doesn't actually use WiFiGPSLocation. It has its own service for assigning a location to responses.

**Comment by hongsudt** [comment]
@joshuaselsky @jojenki 
Does the server validate the possible value of locationStatus?  Do we need to do anything on the server to support this new value?

**Comment by cketcham** [comment]
It looks like the server does validate the value of locationStatus.

I think we should add another value of "gps_off" that is sent if the gps provider is set off. Here is the logic that I think it should use based on how determining the location works now.
1. If the gps gives a location, use that.
2. Otherwise fall back on the network location.
3. If there is no network location and the GPS is turned off, report "gps_off"
4. Otherwise report "unavailable"

The thing is that the network provider might be available even if the gps is turned off so we might get a location even if gps is off. In the location that is returned we can tell if it came from the gps or network provider.

**Comment by cketcham** [comment]
@joshuaselsky take a look at this

**Comment by jshslsky** [comment]
To clarify a conversation that Cameron and I just had: the only values for location_status are valid, unavailable and gps_off. The server code was out of date and still supported the WiFiGPSLocationStatus values.

**Comment by jshslsky** [comment]
@cketcham this has been pushed to odev.

**Comment by jshslsky** [comment]
@cketcham check your work laptop to see if the fix is there.
