### ISSUE TITLE
multiple mobility streams

### ISSUE THREAD

**Issue by jshslsky** [ohmage/android-lib#66]
If I tap the Streams icon within ohmage, I see two Mobility streams. 

Yesterday I updated to the latest ohmage-dev version from Google Play. I also just manually removed and installed Semantic Location Service.

![device-2013-05-17-123745](https://f.cloud.github.com/assets/238878/519181/45a4da3c-bf10-11e2-93e0-c238b530a0f9.png)

**Comment by jojenki** [comment]
I also have two Mobilitys, but I have been up-to-date for a while, I believe.

Also, in my upload queue. I have two LogProbes.

John

**Comment by cketcham** [comment]
It's showing one entry per probe, not per apk. Mobility has two probes, mobility and LogProbe, that is why there are two.

I think the reason this confused you is because of the bug which causes it to show "unknown probe metadata" instead of correctly showing information about the specific probe. I will push that version to the play store soon.

**Comment by jshslsky** [comment]
Fixed.
