### ISSUE TITLE
add the opt-in parameter to stream/upload

### ISSUE THREAD

**Issue by jshslsky** [ohmage/android-lib#75]
If the user has opted in, send the preserve_invalid_points parameter to the stream/upload API.

**Comment by cketcham** [comment]
here is a message to show when having a user opt in:
Help us improve our software by automatically reporting errors. Your login information will not be included.

**Comment by jojenki** [comment]
That sounds ok. I feel like we should mention something that is a little more verbose as far as the fact that some raw observer data will be submitted instead of simply "errors", which is a little ambiguous. The thing is, the person that creates the observer is probably the same person that created the application, so that "person" will already have access to the raw data if they were going to be nefarious.

**Comment by hongsudt** [comment]
I agree if we can make it easy to understand. The problem is that nobody
knows what an observer/stream is when they first login to the software or
even after they use it for a while.

If I am a user and I don't understand the message, I will most likely say
"No".
